# Project 02 - Due Friday, October 13 at 12pm

*Objectives*: Design a relational database schema for transaction processing. Use SQL to load the data into the database and retrieve information from the database.

*Grading criteria*: The tasks should all be completed, and questions should all be answered with SQL queries, shell commands, diagrams and markdown cells.  The notebook itself should be completely reproducible (using AWS EC2 instance based on the provided AMI) from start to finish; another person should be able to use the code to obtain the same results as yours.  Note that you will receive no more than partial credit if you do not add text/markdown cells explaining your thinking at each major step in each problem.

*Attestation*: **Work in groups**.  At the end of your submitted notebook, identify the work each partner performed and attest that each contributed substantially to the work.

*Deadline*: Friday, October 13, 12pm.  One member of each group must submit your notebook to Blackboard; you should not submit it separately.

### Group Members:
* Guangyu Xing
* Jiwei (Wayne) Zeng
* Hangman (Agnes) Jiang
* Pei-Hsuan Hsia

## Part 1 - Requirements

The city is going to launch a new bike sharing system. Your task is to design a relational database to support its operation. The bike sharing system works as follows:

1. Riders can buy annual, semiannual or monthly membership. We need to have a record of each member's name and address in order to send them a key. Keys can be used to check out bikes at any bike station. Members have the option to renew their memberships before they expire. A member becomes inactive when his or her membership expires, therefore we need to know when their memberships expire. 

1. Each bike station has a pubic name (i.e. "18th & C St NW"). Occasionally in response to public requests, stations can be renamed. Each bike station have been built with a number of docking points.

1. Each bike is either serviceable or disabled. If it is disabled, it is removed from the station for repair.

1. For simplicity's sake, each serviceable bike is either docked at a station or checked out by a member. If it is checked out by a member, the system needs to know who has checked it out and when.

Your database should minimally support the above requirements.

## Part 2 - Designing a Database Schema (35 points)

Based on what you read above, design a relational database schema consisting of *at least* 3 tables. Document your schema with a schema diagram.  There are several tools available for this, such as [Google Drawings](https://docs.google.com/drawings/) and Microsoft Visio. Make sure to include the schema diagram in your submission. Embed and display the diagram in your notebook. **Discuss your major design decisions.** Be aware that your schema is designed to support transaction processing and should be optimized for writes and data consistency.

We are looking for the following when grade this part of the project:

* All required attributes are recorded.
* In the schema diagram, all primary keys are underlined. Directed lines are drawn from the foreign keys to the primary keys.
* Your database schema should be designed to promite data consistency and integrity and reduce the duplication of data. Strive for 3NF.
* Your database schema should be designed to support the requirements described in Part 1, as well as problems in Part 4 and 5.
* Key design decisions are discussed and documented in Markdown cells.

See slide 23 of week-04 lecture for an example of schema diagram. 

### Table Rider: The information of riders
__RiderID:__ The ID of each rider. The primary key of the table Rider. The type of its value is text and its value cannot be null.  
__Name:__ The name of each rider. The type of its value is text and its value cannot be null.  
__lastMemberType:__ The latest membership type of each rider.  It just records the last membership the rider renews and includes 3 kinds of value: “annual”, “semiannual” and “monthly”. The type of its value is text and its value cannot be null.  
__keyStatus:__ The Status of riders’ key. It includes 5 kinds of value: null, “sent”, ”not sent”, “returned” and “not returned”. The type of its value is text.  
__latestBuyDate:__ The date when riders renewed their last membership. The type of its value is timestamp and its value cannot be null.  
__activeStatus:__ The status of whether the membership of riders is active. It includes 2 kinds of value : “active” and “expired”. The type of its value is text and its value cannot be null.  
__expireDate:__ The date when riders’ latest membership will expire. The type of its value is timestamp and its value cannot be null.  

### Table bikeStation: The information of bike stations
__stationID:__ The ID of each bike station. The primary key of the table bikeStation. The type of its value is integer and its value cannot be null.  
__stationName:__ The latest name of each bike station. It just records the latest name of each bike station. The type of its value is text and its value cannot be null.  
__formerName:__ The last name of each bike station. After stations renamed, it will record the last name of the stations. The type of its value is text.  
__Capacity:__ The maximum capacity of each bike station. The type of its value is integer and its value cannot be null.

### Table bike: The information of bikes
__bikeID:__ The ID of each bike. The primary key of the table bike. The type of its value is integer and its value cannot be null.  
__bikeStatus:__ The status on whether the bike is checked out or not. It includes 2 kinds of value: null and “checked out”.   The type of its value is text.  
__Serviceable:__ Whether each car is serviceable. It includes 2 kinds of value: ”t” and “ f”. The type of its value is text and its value cannot be null.  
__lastStationID:__ The ID of the last station where bikes are docked. The type of its value is integer. When a bike is repaired, it will be null.

### Table MembershipRecord: The renewing record of membership
__buyID:__ The ID of each renewing membership. The primary key of the table MembershipRecord. The type of its value is text and its value cannot be null.  
__riderID:__ The ID of rider who renew their membership. The type of its value is text and its value cannot be null. It is a foreign key referencing the riderID in the table rider.  
__memberType:__ The types of membership which riders renewed.  It includes 3 kinds of value: “annual”, “semiannual” and “monthly”. The type of its value is text and its value cannot be null.  
__buyDate:__ The date when riders renewed their membership. The type of its value is timestamp and its value cannot be null.  
__expireDate:__ The date when riders’ membership will expire. The type of its value is timestamp and its value cannot be null.

### Table Transaction: The information of each transaction
__TransactionID:__ The ID of each transaction. The primary key of the table Transaction. The type of its value is text and its value cannot be null.  
__bikeID:__ The ID of the bike which is checked out in each transaction.  The type of its value is integer. It is a foreign key referencing the bikeID in the table Bike.  
__riderID:__ The ID of rider in each transaction. The type of its value is text. It is a foreign key referencing the riderID in the table Rider.  
__serviceStatus:__ The status of whether each bike is in service or not. It includes two kinds of value: ”checked out” and “ returned”. The type of its value is text and its value cannot be null.  
__StartStationID :__ The ID of station where the bike was checked out in each transaction. The type of its value is text. It is a foreign key referencing the stationID in the table bikeStation.  
__StartDate:__ The date when each transaction started. The type of its value is timestamp and its value cannot be null.  
__EndStationID:__ The ID of station where the bike was returned in each transaction. The type of its value is text. It is a foreign key referencing the stationID in the table bikeStation.  
__EndDate:__ The date when each transaction ended. The type of its value is timestamp.

## Part 3 - ETL (30 points)
Please use markdown cells to **document major steps**. Use SQL queries and markdown cells to demonstrate that records are created or updated successfully.

### Problem 3.1
Examine the data located at https://s3.amazonaws.com/dmfa-2017/bike_stations.csv.
Create and connect to a new PostgreSQL database named `proj2`. Use SQL DDL to create your tables in it based on the database schema you designed in Part 2 and the data. Don't forget about the contraints (primary keys, foreign keys, proper attribute types, NOT NULL etc).

First, drop the database named `proj2` if it exists. It is necessary so that we can run this notebook repeatedly. If you get the error that says "database proj2 does not exist", that is fine. However if it complains that "There is 1 other session using the database", please restart the Kernel and try it again.

In [1]:
!dropdb -U student proj2

In [2]:
!createdb -U student proj2

In [3]:
%load_ext sql

In [4]:
%sql postgresql://student@/proj2

'Connected: student@proj2'

Create all of the tables (Rider, MembershipRecord, BikeStation, Bike, Transaction) according to the schema.

In [5]:
%%sql
DROP TABLE IF EXISTS Rider;
CREATE TABLE Rider(
    riderID TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    lastMemberType TEXT, 
    keyStatus TEXT NOT NULL,
    lastBuyDate TIMESTAMP NOT NULL, 
    activeStatus TEXT NOT NULL,
    lastExpireDate TIMESTAMP NOT NULL);


DROP TABLE IF EXISTS BikeStation;
CREATE TABLE BikeStation(
    stationID INTEGER PRIMARY KEY, 
    stationName TEXT NOT NULL,
    formerName TEXT,
    capacity INTEGER NOT NULL);


DROP TABLE IF EXISTS Bike;
CREATE TABLE Bike(
    bikeID TEXT PRIMARY KEY, 
    bikeStatus TEXT,
    serviceable TEXT NOT NULL,
    lastStationID INTEGER);


DROP TABLE IF EXISTS MembershipRecord;
CREATE TABLE MembershipRecord(
    buyID TEXT PRIMARY KEY,
    riderID TEXT, 
    memberType TEXT NOT NULL,
    buyDate TIMESTAMP NOT NULL,
    expireDate TIMESTAMP NOT NULL,
    FOREIGN KEY(riderID) REFERENCES Rider(riderID));



DROP TABLE IF EXISTS Transaction;
CREATE TABLE Transaction(
    transactionID TEXT PRIMARY KEY, 
    bikeID TEXT, 
    riderID TEXT, 
    serviceStatus TEXT NOT NULL, 
    startStationID INTEGER,
    startDate TIMESTAMP NOT NULL,
    endStationID INTEGER,
    endDate TIMESTAMP, 
    FOREIGN KEY(startStationID) REFERENCES BikeStation(stationID),
    FOREIGN KEY(endStationID) REFERENCES BikeStation(stationID),
    FOREIGN KEY(bikeID) REFERENCES Bike(bikeID),
    FOREIGN KEY(riderID) REFERENCES Rider(riderID));

Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.


[]

### Problem 3.2
Use the data located at https://s3.amazonaws.com/dmfa-2017/bike_stations.csv to populate your database. You may import the CSV file content into a temporary table in your database `proj2`. Just remember to remove it after you are done. 

Since the data doesn't include information about members, you will need to make up a few (4 or 5) members in your database. Some of their memberships have expired.

In [6]:
!wget https://s3.amazonaws.com/dmfa-2017/bike_stations.csv

--2017-10-12 20:34:55--  https://s3.amazonaws.com/dmfa-2017/bike_stations.csv
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.81.236
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.81.236|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 169879 (166K) [text/csv]
Saving to: ‘bike_stations.csv’

bike_stations.csv   100%[===================>] 165.90K  1.01MB/s    in 0.2s    

2017-10-12 20:34:55 (1.01 MB/s) - ‘bike_stations.csv’ saved [169879/169879]



In [7]:
!head bike_stations.csv | csvlook

|--------------+------------------+----------------+----------------------------------------------+-------------------|
|  Bike number | Bike serviceable | Station number | Station name                                 | Station capacity  |
|--------------+------------------+----------------+----------------------------------------------+-------------------|
|  W00005      | t                | 32011          | Maple & Ritchie Ave                          | 28                |
|  W00174      | t                | 31246          | M St & Pennsylvania Ave NW                   | 10                |
|  W00196      | t                | 31408          | Takoma Metro                                 | 12                |
|  W00216      | t                | 31309          | Fessenden St & Wisconsin Ave NW              | 8                 |
|  W00267      | t                | 31125          | 15th & W St NW                               | 24                |
|  W00310      | t                | 3105

Create a temporary table called Temp in the database proj2.

In [6]:
%%sql
DROP TABLE IF EXISTS Temp;
CREATE TABLE Temp(
    bikeNumber TEXT, 
    bikeServiceable TEXT,
    stationNumber INTEGER,
    stationName TEXT,
    stationCapacity INTEGER);


Done.
Done.


[]

In [8]:
!pwd

/home/ubuntu/project-02


Import the CSV content into Temp. You should revise it using your local path showed in the pwd command.

In [9]:
%%sql
COPY Temp FROM '/home/ubuntu/project-02/bike_stations.csv'
CSV
HEADER;

4317 rows affected.


[]

Check whether the Temp table is filled correctly.

In [11]:
%%sql
SELECT * from Temp;

4317 rows affected.


[('W00005', 't', 32011, 'Maple & Ritchie Ave', 28),
 ('W00174', 't', 31246, 'M St & Pennsylvania Ave NW', 10),
 ('W00196', 't', 31408, 'Takoma Metro', 12),
 ('W00216', 't', 31309, 'Fessenden St & Wisconsin Ave NW', 8),
 ('W00267', 't', 31125, '15th & W St NW', 24),
 ('W00310', 't', 31056, 'S Troy St & 26th St S', 9),
 ('W00338', 't', 31244, '4th & E St SW', 19),
 ('W00388', 't', 32023, 'Montgomery College/W Campus Dr & Mannakee St', 8),
 ('W00403', 't', 31217, 'USDA / 12th & Independence Ave SW', 10),
 ('W00409', 't', 31402, '14th St Heights / 14th & Crittenden St NW', 6),
 ('W00475', 't', 31400, 'Georgia & New Hampshire Ave NW', 18),
 ('W00489', 't', 31509, 'New Jersey Ave & R St NW', 27),
 ('W00522', 't', 31614, '11th & H St NE', 23),
 ('W00546', 't', 31252, '21st St & Pennsylvania Ave NW', 7),
 ('W00562', 't', 31312, 'Wisconsin Ave & O St NW', 16),
 ('W00678', 't', 31226, '34th St & Wisconsin Ave NW', 9),
 ('W00721', 't', 31203, '14th & Rhode Island Ave NW', 20),
 ('W00731', 't', 32045, 'Shady Grove Metro West', 16),
 ('W00155', 't', 31636, 'New Jersey Ave & N St NW/Dunbar HS', 19),
 ('W00201', 't', 31042, 'Market Square / King St & Royal St', 13),
 ('W00254', 't', 31212, '21st & M St NW', 17),
 ('W00261', 't', 31645, '6th & K St NE', 23),
 ('W00283', 't', 31010, 'S Glebe & Potomac Ave', 15),
 ('W00301', 't', 31101, '14th & V St NW', 42),
 ('W00305', 't', 31633, "Independence Ave & L'Enfant Plaza SW/DOE", 13),
 ('W00325', 't', 31281, '8th & O St NW', 26),
 ('W00084', 't', 31400, 'Georgia & New Hampshire Ave NW', 18),
 ('W00133', 't', 31801, 'Anacostia Metro', 14),
 ('W00194', 't', 31623, 'Columbus Circle / Union Station', 51),
 ('W00204', 't', 31248, 'Smithsonian-National Mall / Jefferson Dr & 12th St SW', 18),
 ('W00207', 't', 32010, 'Philadelphia & Maple Ave', 28),
 ('W00230', 't', 31414, 'Georgia Ave & Piney Branch Rd NW', 12),
 ('W00300', 't', 31317, 'Wisconsin Ave & Ingomar St NW', 12),
 ('W00337', 't', 32045, 'Shady Grove Metro West', 16),
 ('W00341', 't', 31029, 'N Veitch  & 20th St N', 20),
 ('W00342', 't', 31030, 'Lee Hwy & N Adams St', 4),
 ('W00383', 't', 31041, 'Prince St & Union St', 23),
 ('W00393', 't', 31916, 'Potomac & Swann Ave', 27),
 ('W00407', 't', 31282, '16th & R St NW', 20),
 ('W00422', 't', 31707, 'Benning Rd & East Capitol St NE / Benning Rd Metro', 10),
 ('W00429', 't', 31604, '3rd & H St NW', 16),
 ('W00469', 't', 31600, '5th & K St NW', 28),
 ('W00478', 't', 31227, '13th St & New York Ave NW', 5),
 ('W00026', 't', 31070, 'Arlington Blvd & Fillmore St', 18),
 ('W00115', 't', 31265, '5th St & Massachusetts Ave NW', 24),
 ('W00124', 't', 31068, 'Columbia Pike & S Dinwiddie St / Arlington Mill Community Center', 11),
 ('W00169', 't', 31249, 'Jefferson Memorial', 31),
 ('W00260', 't', 31504, '10th & Monroe St NE', 3),
 ('W00366', 't', 31508, 'Gallaudet / 8th St & Florida Ave NE', 26),
 ('W00375', 't', 31012, '26th & S Clark St', 11),
 ('W00397', 't', 31241, 'Thomas Circle', 6),
 ('W00440', 't', 31228, '8th & H St NW', 24),
 ('W00446', 't', 31249, 'Jefferson Memorial', 31),
 ('W00496', 't', 31807, 'Pleasant St & MLK Ave SE', 10),
 ('W00509', 't', 32010, 'Philadelphia & Maple Ave', 28),
 ('W00581', 't', 31109, '7th & T St NW', 29),
 ('W00586', 't', 31620, '5th & F St NW', 19),
 ('W00589', 't', 31013, '23rd & Eads St', 17),
 ('W00616', 't', 31275, 'New Hampshire Ave & 24th St NW', 7),
 ('W00647', 't', 32043, 'Veterans Pl & Pershing Dr ', 12),
 ('W00050', 't', 31644, '12th St & Pennsylvania Ave SE', 25),
 ('W00051', 't', 32022, 'Garland Ave & Walden Rd', 1),
 ('w00059', 't', 31083, 'Potomac Greens Dr & Slaters Ln', 18),
 ('W00132', 't', 31036, 'George Mason Dr & Wilson Blvd', 15),
 ('W00134', 't', 31520, '24th & R St NE / National Arboretum', 10),
 ('W00224', 't', 31620, '5th & F St NW', 19),
 ('W00236', 't', 31712, 'Oklahoma Ave & D St NE', 27),
 ('W00352', 't', 31013, '23rd & Eads St', 17),
 ('W00395', 't', 31626, '15th St & Massachusetts Ave SE', 23),
 ('W00481', 't', 31265, '5th St & Massachusetts Av

Check the bike information and see whether there is null data that we need to rule out.

In [10]:
%%sql
SELECT  bikenumber,  count (*) 
FROM  Temp
GROUP BY bikenumber;

4299 rows affected.


[(None, 19),
 ('W00748', 1),
 ('W22281', 1),
 ('W21826', 1),
 ('W21878', 1),
 ('W22482', 1),
 ('W21457', 1),
 ('W01486', 1),
 ('W00489', 1),
 ('W00522', 1),
 ('W21677', 1),
 ('W20779', 1),
 ('W00721', 1),
 ('W21337', 1),
 ('W22452', 1),
 ('W20645', 1),
 ('W20344', 1),
 ('W23250', 1),
 ('W22841', 1),
 ('W00992', 1),
 ('W20278', 1),
 ('W01264', 1),
 ('W22399', 1),
 ('W01010', 1),
 ('W21889', 1),
 ('W22491', 1),
 ('W20199', 1),
 ('W22213', 1),
 ('W22531', 1),
 ('W22354', 1),
 ('W22907', 1),
 ('W20962', 1),
 ('W22237', 1),
 ('W20198', 1),
 ('W00863', 1),
 ('W21956', 1),
 ('W22288', 1),
 ('W01204', 1),
 ('W00546', 1),
 ('W00787', 1),
 ('W22404', 1),
 ('W00317', 1),
 ('W22510', 1),
 ('W21735', 1),
 ('W21714', 1),
 ('W00178', 1),
 ('W20716', 1),
 ('W23130', 1),
 ('W20659', 1),
 ('W20254', 1),
 ('W00403', 1),
 ('W20433', 1),
 ('W22526', 1),
 ('W00678', 1),
 ('W21901', 1),
 ('W22769', 1),
 ('W21643', 1),
 ('W21612', 1),
 ('W22094', 1),
 ('W00772', 1),
 ('W20058', 1),
 ('W20862', 1),
 ('W22472', 1),
 ('W21640', 1),
 ('W21107', 1),
 ('W22661', 1),
 ('W01380', 1),
 ('W20454', 1),
 ('W00562', 1),
 ('W21018', 1),
 ('W20679', 1),
 ('W21210', 1),
 ('W01394', 1),
 ('W20230', 1),
 ('W00795', 1),
 ('W00980', 1),
 ('W00383', 1),
 ('W21820', 1),
 ('W23092', 1),
 ('W21449', 1),
 ('W22031', 1),
 ('W22874', 1),
 ('W22744', 1),
 ('W00505', 1),
 ('W01262', 1),
 ('W22888', 1),
 ('W00526', 1),
 ('W00084', 1),
 ('W21177', 1),
 ('W21882', 1),
 ('W22200', 1),
 ('W01396', 1),
 ('W20418', 1),
 ('W20266', 1),
 ('W21141', 1),
 ('W01033', 1),
 ('W20718', 1),
 ('W20152', 1),
 ('W00885', 1),
 ('W00300', 1),
 ('W21796', 1),
 ('W00201', 1),
 ('W01446', 1),
 ('W01266', 1),
 ('W00649', 1),
 ('W22069', 1),
 ('W21606', 1),
 ('W21773', 1),
 ('W20134', 1),
 ('W22349', 1),
 ('W22367', 1),
 ('W20894', 1),
 ('W21865', 1),
 ('W00261', 1),
 ('W00305', 1),
 ('W00301', 1),
 ('W21694', 1),
 ('W22759', 1),
 ('W00793', 1),
 ('W22533', 1),
 ('W20336', 1),
 ('W21090', 1),
 ('W01184', 1),
 ('W22788', 1),
 ('W00464', 1),
 ('W21522', 1),
 ('W01170', 1),
 ('W22471', 1),
 ('W01113', 1),
 ('W23150', 1),
 ('W20543', 1),
 ('W20691', 1),
 ('W00693', 1),
 ('W22331', 1),
 ('W22935', 1),
 ('W00254', 1),
 ('W23034', 1),
 ('W22357', 1),
 ('W01166', 1),
 ('W00718', 1),
 ('W23213', 1),
 ('W21542', 1),
 ('W00155', 1),
 ('W00484', 1),
 ('W20678', 1),
 ('W20574', 1),
 ('W01087', 1),
 ('W20225', 1),
 ('W22005', 1),
 ('W20288', 1),
 ('W20489', 1),
 ('W20318', 1),
 ('W23205', 1),
 ('W20479', 1),
 ('W21423', 1),
 ('W00970', 1),
 ('W22368', 1),
 ('W21518', 1),
 ('W21935', 1),
 ('W01322', 1),
 ('W22088', 1),
 ('W21825', 1),
 ('W23267', 1),
 ('W00260', 1),
 ('W21303', 1),
 ('W22870', 1),
 ('W20988', 1),
 ('W01085', 1),
 ('W20624', 1),
 ('W00124', 1),
 ('W00771', 1),
 ('W21775', 1),
 ('W00883', 1),
 ('W20326', 1),
 ('W20141', 1),
 ('W22169', 1),
 ('W22022', 1),
 ('W20550', 1),
 ('W01304', 1),
 ('W01020', 1),
 ('W20006', 1),
 ('W00115', 1),
 ('W00589', 1),
 ('W21434', 1),
 ('W22319', 1),
 ('W21319', 1),
 ('W21695', 1),
 ('W00169', 1),
 ('W22626', 1),
 ('W22944', 1),
 ('W22195', 1),
 ('W20813', 1),
 ('W21877', 1),
 ('W00586', 1),
 ('W00446', 1),
 ('W21077', 1),
 ('W01386', 1),
 ('W01124', 1),
 ('W20637', 1),
 ('W00481', 1),
 ('W22362', 1),
 ('W22564', 1),
 ('W01056', 1),
 ('W22543', 1),
 ('W20005', 1),
 ('W20323', 1),
 ('W21751', 1),
 ('W20830', 1),
 ('W22124', 1),
 ('W20077', 1),
 ('W21782', 1),
 ('W22252', 1),
 ('W22018', 1),
 ('W23164', 1),
 ('W00531', 1),
 ('W20096', 1),
 ('W22051', 1),
 ('W22912', 1),
 ('W00808', 1),
 ('W21460', 1),
 ('W23013', 1),
 ('W01359', 1),
 ('W22854', 1),
 ('W22887', 1),
 ('W23175', 1),
 ('W22384', 1),
 ('W00581', 1),
 ('W21922', 1),
 ('W20850', 1),
 ('W00869', 1),
 ('W23219', 1),
 ('W21544', 1),
 ('W22889', 1),
 ('W00943', 1),
 ('W01065', 1),
 ('W22339', 1),
 ('W22929', 1),
 ('W01191', 1),
 ('W20863', 1),
 ('W20371', 1),
 ('W22389', 1),
 ('W01412', 1),
 ('W20963', 1),
 ('W21354', 1),
 ('W21483', 1),
 ('W22683', 1),
 ('W21885', 1),
 ('W01215', 1),
 ('W21065', 1),
 ('W22845', 1),
 ('

Copy all non-null data of bike number, serviceable status and station number into __Bike__ dataset.


In [11]:
%%sql
INSERT INTO Bike (bikeID, serviceable, lastStationID)
SELECT bikenumber, bikeserviceable, stationnumber 
FROM   Temp 
WHERE  bikenumber IS NOT NULL;

4298 rows affected.


[]

Check the station information and see whether there is null data that we need to rule out.

In [12]:
%%sql
SELECT  stationnumber, count (*) 
FROM Temp
GROUP BY stationnumber;

453 rows affected.


[(31000, 11),
 (31511, 7),
 (32002, 16),
 (None, 475),
 (31069, 1),
 (31093, 2),
 (31701, 2),
 (31267, 4),
 (31035, 5),
 (31266, 10),
 (31061, 3),
 (31012, 5),
 (31024, 11),
 (31319, 1),
 (31252, 1),
 (31114, 17),
 (32047, 4),
 (31632, 22),
 (32064, 5),
 (32011, 26),
 (31200, 4),
 (32051, 3),
 (32040, 12),
 (31291, 2),
 (31600, 25),
 (31621, 7),
 (31217, 9),
 (31052, 10),
 (32216, 6),
 (32050, 4),
 (31022, 3),
 (31519, 14),
 (32045, 11),
 (32021, 1),
 (31803, 11),
 (31234, 4),
 (31907, 12),
 (31218, 5),
 (31285, 3),
 (31607, 13),
 (31096, 8),
 (31517, 16),
 (31603, 12),
 (31901, 3),
 (31917, 16),
 (31105, 6),
 (31021, 5),
 (32026, 11),
 (31501, 2),
 (32052, 5),
 (32025, 2),
 (31631, 17),
 (31620, 13),
 (31241, 5),
 (31071, 8),
 (31802, 3),
 (32029, 5),
 (31910, 9),
 (31708, 13),
 (31003, 7),
 (31081, 4),
 (32208, 2),
 (31070, 11),
 (31072, 1),
 (31048, 3),
 (31315, 3),
 (32003, 2),
 (31017, 1),
 (31029, 12),
 (31106, 8),
 (31232, 20),
 (31702, 3),
 (32036, 1),
 (31253, 2),
 (31605, 8),
 (32037, 8),
 (32016, 3),
 (32202, 1),
 (32009, 4),
 (31404, 7),
 (31401, 6),
 (31121, 9),
 (31712, 24),
 (31630, 15),
 (31023, 10),
 (31613, 12),
 (31286, 16),
 (31043, 10),
 (32213, 9),
 (31700, 3),
 (31215, 16),
 (31238, 2),
 (31612, 24),
 (31309, 7),
 (31042, 11),
 (31204, 5),
 (31226, 7),
 (32221, 1),
 (31059, 6),
 (31276, 3),
 (31030, 1),
 (31292, 1),
 (31080, 3),
 (31905, 9),
 (32062, 2),
 (31026, 3),
 (32010, 24),
 (31506, 15),
 (31057, 7),
 (32059, 2),
 (31111, 15),
 (31225, 3),
 (31242, 4),
 (31076, 11),
 (31513, 3),
 (31040, 5),
 (31508, 23),
 (32203, 3),
 (32023, 4),
 (31414, 5),
 (32223, 6),
 (32043, 9),
 (31063, 7),
 (31316, 1),
 (31047, 5),
 (31120, 16),
 (31033, 3),
 (31112, 9),
 (31064, 4),
 (31500, 15),
 (31239, 5),
 (31037, 2),
 (31918, 10),
 (31512, 14),
 (31909, 10),
 (31009, 7),
 (31624, 21),
 (31644, 23),
 (31060, 12),
 (31038, 5),
 (32007, 7),
 (32027, 9),
 (31092, 4),
 (31053, 8),
 (31270, 8),
 (31041, 19),
 (31101, 41),
 (32022, 1),
 (31011, 12),
 (31623, 49),
 (31231, 5),
 (31229, 22),
 (31051, 10),
 (31256, 15),
 (31704, 1),
 (31044, 9),
 (31031, 9),
 (31317, 4),
 (31007, 4),
 (31115, 16),
 (31084, 4),
 (31103, 11),
 (31908, 6),
 (31912, 8),
 (31290, 5),
 (31904, 1),
 (31400, 14),
 (32217, 1),
 (31055, 15),
 (31271, 3),
 (31282, 16),
 (31015, 12),
 (31713, 1),
 (31089, 1),
 (31288, 3),
 (31273, 17),
 (32212, 3),
 (31304, 2),
 (32215, 13),
 (32048, 3),
 (31703, 4),
 (32200, 4),
 (31208, 9),
 (31289, 18),
 (31122, 5),
 (31274, 6),
 (31211, 3),
 (31411, 4),
 (31109, 24),
 (32028, 11),
 (32063, 11),
 (32211, 1),
 (31005, 9),
 (31408, 8),
 (31032, 7),
 (31250, 1),
 (31310, 7),
 (31073, 9),
 (31902, 12),
 (31085, 5),
 (31642, 4),
 (31610, 6),
 (31237, 12),
 (31812, 8),
 (32041, 1),
 (31707, 1),
 (31604, 7),
 (31611, 27),
 (31001, 3),
 (32034, 2),
 (31203, 16),
 (31094, 15),
 (31116, 19),
 (31079, 10),
 (31222, 4),
 (31714, 3),
 (31006, 14),
 (31100, 1),
 (31279, 3),
 (31207, 7),
 (31067, 8),
 (32058, 6),
 (31407, 5),
 (31913, 5),
 (32057, 4),
 (31306, 7),
 (31104, 2),
 (31056, 5),
 (31402, 3),
 (31608, 9),
 (31314, 16),
 (31265, 17),
 (31002, 10),
 (31236, 3),
 (31805, 5),
 (31259, 1),
 (31293, 9),
 (31219, 8),
 (31066, 4),
 (32056, 5),
 (32020, 4),
 (31212, 10),
 (31095, 6),
 (31303, 2),
 (32046, 17),
 (31318, 20),
 (31915, 7),
 (31302, 6),
 (31806, 4),
 (32039, 1),
 (31246, 6),
 (31807, 4),
 (31906, 12),
 (31036, 8),
 (31640, 20),
 (31020, 2),
 (32015, 4),
 (31082, 3),
 (32012, 2),
 (31263, 8),
 (31245, 17),
 (31629, 9),
 (31638, 12),
 (31025, 1),
 (31277, 2),
 (31509, 23),
 (31521, 12),
 (31606, 13),
 (31205, 1),
 (31505, 15),
 (32049, 7),
 (31615, 27),
 (32055, 9),
 (32030, 1),
 (31916, 19),
 (31514, 6),
 (32000, 1),
 (31214, 22),
 (31516, 8),
 (32222, 1),
 (32019, 5),
 (32042, 1),
 (31520, 10),
 (31622, 33),
 (31269, 10),
 (31313, 6),
 (31233, 6),
 (31227, 1),
 (31201, 14),
 (31518, 22),
 (32201, 3),
 (31107, 18),
 (31275, 4),
 (31619, 22),
 (31050, 2),
 (31919, 3),
 (32001, 3),
 (31235, 7),
 (31264, 9),
 (31515, 5),
 

Copy all non-null data of distinct station number, name and capacity into __BikeStation__ dataset.


In [13]:
%%sql
INSERT INTO BikeStation (stationID, stationName, capacity)
SELECT DISTINCT stationnumber, stationname, stationcapacity 
FROM   Temp 
WHERE  stationnumber IS NOT NULL;

452 rows affected.


[]

Drop the temporary table.

In [14]:
%%sql
DROP TABLE Temp;

Done.


[]

Make up 5 members in the Rider dataset. The last rider’s membership is expired.

In [15]:
%%sql
DELETE FROM Rider;

INSERT INTO Rider  
VALUES 
    ('001', 'Connie', '1600 S Eads St', 'annual', 'sent', '06/15/2017', 'Yes', '06/15/2018'), 
    ('002', 'Pei-Hsuan', '2121 I St', 'annual', 'sent', '03/13/2017' ,  'Yes', '03/13/2018'), 
    ('003', 'Guangyu', '2201 G St', 'semiannual', 'sent' , '06/30/2017' , 'Yes', '12/31/2017'),
    ('004', 'Wayne', '2000 H St', 'semiannual', 'sent' , '07/15/2017', 'Yes', '01/15/2018'),
    ('005', 'Agnes', '1900 S Eads St', 'monthly', 'returned' , '08/26/2017', 'No' ,'09/26/2017')
;

0 rows affected.
5 rows affected.


[]

## Part 4 - Operations (15 points)
Use SQL queries and markdown cells to demonstrate that records are created or updated successfully.

In the __Bike__ dataset, there are 4298 bikes in our system. Data of bike ID, bike status, serviceable status and last station ID the bike is docked is in the dataset.

In [16]:
%%sql
SELECT * from Bike;

4298 rows affected.


[('W00005', None, 't', 32011),
 ('W00174', None, 't', 31246),
 ('W00196', None, 't', 31408),
 ('W00216', None, 't', 31309),
 ('W00267', None, 't', 31125),
 ('W00310', None, 't', 31056),
 ('W00338', None, 't', 31244),
 ('W00388', None, 't', 32023),
 ('W00403', None, 't', 31217),
 ('W00409', None, 't', 31402),
 ('W00475', None, 't', 31400),
 ('W00489', None, 't', 31509),
 ('W00522', None, 't', 31614),
 ('W00546', None, 't', 31252),
 ('W00562', None, 't', 31312),
 ('W00678', None, 't', 31226),
 ('W00721', None, 't', 31203),
 ('W00731', None, 't', 32045),
 ('W00155', None, 't', 31636),
 ('W00201', None, 't', 31042),
 ('W00254', None, 't', 31212),
 ('W00261', None, 't', 31645),
 ('W00283', None, 't', 31010),
 ('W00301', None, 't', 31101),
 ('W00305', None, 't', 31633),
 ('W00325', None, 't', 31281),
 ('W00084', None, 't', 31400),
 ('W00133', None, 't', 31801),
 ('W00194', None, 't', 31623),
 ('W00204', None, 't', 31248),
 ('W00207', None, 't', 32010),
 ('W00230', None, 't', 31414),
 ('W00300', None, 't', 31317),
 ('W00337', None, 't', 32045),
 ('W00341', None, 't', 31029),
 ('W00342', None, 't', 31030),
 ('W00383', None, 't', 31041),
 ('W00393', None, 't', 31916),
 ('W00407', None, 't', 31282),
 ('W00422', None, 't', 31707),
 ('W00429', None, 't', 31604),
 ('W00469', None, 't', 31600),
 ('W00478', None, 't', 31227),
 ('W00026', None, 't', 31070),
 ('W00115', None, 't', 31265),
 ('W00124', None, 't', 31068),
 ('W00169', None, 't', 31249),
 ('W00260', None, 't', 31504),
 ('W00366', None, 't', 31508),
 ('W00375', None, 't', 31012),
 ('W00397', None, 't', 31241),
 ('W00440', None, 't', 31228),
 ('W00446', None, 't', 31249),
 ('W00496', None, 't', 31807),
 ('W00509', None, 't', 32010),
 ('W00581', None, 't', 31109),
 ('W00586', None, 't', 31620),
 ('W00589', None, 't', 31013),
 ('W00616', None, 't', 31275),
 ('W00647', None, 't', 32043),
 ('W00050', None, 't', 31644),
 ('W00051', None, 't', 32022),
 ('w00059', None, 't', 31083),
 ('W00132', None, 't', 31036),
 ('W00134', None, 't', 31520),
 ('W00224', None, 't', 31620),
 ('W00236', None, 't', 31712),
 ('W00352', None, 't', 31013),
 ('W00395', None, 't', 31626),
 ('W00481', None, 't', 31265),
 ('W00487', None, 't', 31611),
 ('W00492', None, 't', 31621),
 ('W00531', None, 't', 31009),
 ('W00553', None, 't', 31120),
 ('W00555', None, 't', 31088),
 ('W00663', None, 't', 31279),
 ('W00065', None, 't', 31102),
 ('W00090', None, 't', 31613),
 ('W00119', None, 't', 31641),
 ('W00139', None, 't', 31401),
 ('W00146', None, 't', 31079),
 ('W00189', None, 't', 31021),
 ('W00211', None, 't', 31107),
 ('W00242', None, 't', 31103),
 ('W00347', None, 't', 32019),
 ('W00356', None, 't', 31115),
 ('W00427', None, 't', 31080),
 ('W00434', None, 't', 31616),
 ('W00057', None, 't', 31223),
 ('W00060', None, 't', 32046),
 ('W00095', None, 't', 32209),
 ('W00098', None, 't', 31313),
 ('W00108', None, 't', 31000),
 ('W00117', None, 't', 31232),
 ('W00129', None, 't', 31091),
 ('W00200', None, 't', 31075),
 ('W00205', None, 't', 31907),
 ('W00302', None, 't', 31221),
 ('W00351', None, 't', 31240),
 ('W00411', None, 't', 32029),
 ('W00430', None, 't', 31107),
 ('W00433', None, 't', 31278),
 ('W00021', None, 't', 31231),
 ('W00049', None, 't', 31079),
 ('W00081', None, 't', 31258),
 ('W00087', None, 't', 32056),
 ('W00114', None, 't', 31281),
 ('W00181', None, 't', 31318),
 ('W00210', None, 't', 32008),
 ('W00226', None, 't', 31238),
 ('W00228', None, 't', 31223),
 ('W00249', None, 't', 31641),
 ('W00039', None, 't', 31102),
 ('W00044', None, 't', 31400),
 ('W00070', None, 't', 31639),
 ('W00082', None, 't', 31006),
 ('W00128', None, 't', 31007),
 ('W00149', None, 't', 31626),
 ('W00151', None, 't', 31222),
 ('W00173', None, 't', 31622),
 ('W00179', None, 't', 31639),
 ('W00197', None, 't', 31641),
 ('W00199', None, 't', 31005),
 ('W00239', None, 't', 31645),
 ('W00247', None, 't', 31631),
 ('W00163', None, 't', 31208),
 ('W00176', None, 't', 31234),
 ('W00208', None, 't', 31108),
 ('W00246', None, 't', 31243),
 

In the __BikeStation__ dataset, there are 452 stations in our system. Station ID, current station name, former name and its capacity is included in this dataset. Former name is all none since we haven’t changed any of the station name.

In [17]:
%%sql
SELECT * from BikeStation;

452 rows affected.


[(31221, '18th & M St NW', None, 13),
 (31287, "10th St & L'Enfant Plaza SW", None, 8),
 (31507, '1st & Washington Hospital Center NW', None, 8),
 (31119, '14th & Belmont St NW', None, 14),
 (32010, 'Philadelphia & Maple Ave', None, 28),
 (31501, '12th & Newton St NE', None, 5),
 (31313, 'Connecticut Ave & Tilden St NW', None, 8),
 (32034, 'Ripley & Bonifant St', None, 8),
 (31603, '1st & M St NE', None, 17),
 (31909, 'Mount Vernon Ave & Four Mile Run Park', None, 13),
 (31000, 'Eads St & 15th St S', None, 13),
 (31404, '9th & Upshur St NW', None, 14),
 (32002, 'Bethesda Ave & Arlington Rd', None, 22),
 (31205, '21st & I St NW', None, 2),
 (31225, 'C & O Canal & Wisconsin Ave NW', None, 3),
 (31630, '15th & East Capitol St NE', None, 18),
 (31027, 'Key Blvd & N Quinn St', None, 7),
 (31290, '17th St & Independence Ave SW', None, 9),
 (31272, 'Washington & Independence Ave SW/HHS', None, 14),
 (31253, '19th & K St NW', None, 3),
 (31010, 'S Glebe & Potomac Ave', None, 15),
 (31623, 'Columbus Circle / Union Station', None, 51),
 (31505, 'Eckington Pl & Q St NE', None, 16),
 (31051, 'Arlington Blvd & N Queen St', None, 17),
 (31309, 'Fessenden St & Wisconsin Ave NW', None, 8),
 (31509, 'New Jersey Ave & R St NW', None, 27),
 (31077, 'Iwo Jima Memorial/N Meade & 14th St N', None, 16),
 (31407, '14th St & Colorado Ave NW', None, 7),
 (32042, 'Shady Grove Hospital', None, 8),
 (32027, 'Battery Ln & Trolley Trail', None, 15),
 (31089, 'Court House Metro / 15th & N Uhle St ', None, 1),
 (31629, '8th & East Capitol St NE', None, 10),
 (31095, 'Army Navy Dr & S Nash St', None, 14),
 (31020, 'Wilson Blvd & Franklin Rd', None, 8),
 (31288, '4th St & Madison Dr NW', None, 6),
 (31206, '19th & E Street NW', None, 6),
 (32203, 'Tysons One Pl & Chain Bridge Rd', None, 8),
 (31293, '31st & Water St NW', None, 15),
 (31227, '13th St & New York Ave NW', None, 5),
 (31064, 'S Stafford & 34th St S', None, 7),
 (31220, 'US Dept of State / Virginia Ave & 21st St NW', None, 1),
 (31302, 'Wisconsin Ave & Newark St NW', None, 13),
 (31090, '6th & S Ball St', None, 13),
 (31046, 'Henry St & Pendleton St', None, 20),
 (32064, 'Amherst Ave & Prichard Rd', None, 12),
 (31200, 'Massachusetts Ave & Dupont Circle NW', None, 4),
 (31121, 'Calvert St & Woodley Pl NW', None, 13),
 (31900, 'Lee Hwy & N Woodstock St', None, 11),
 (31104, 'Adams Mill & Columbia Rd NW', None, 4),
 (31114, '18th St & Wyoming Ave NW', None, 17),
 (31241, 'Thomas Circle', None, 6),
 (32221, 'Greensboro & International Dr', None, 2),
 (31092, 'Lee Hwy & N Monroe St', None, 9),
 (31063, 'S George Mason Dr & Four Mile Run', None, 14),
 (31517, 'Union Market/6th St & Neal Pl NE', None, 16),
 (32005, 'Traville Gateway Dr & Gudelsky Dr', None, 6),
 (31073, 'Washington Blvd & Walter Reed Dr ', None, 10),
 (31638, '1st & H St NW', None, 18),
 (31052, 'Potomac Ave & 35th St S', None, 15),
 (31108, '4th & M St SW', None, 28),
 (31400, 'Georgia & New Hampshire Ave NW', None, 18),
 (31120, '10th & Florida Ave NW', None, 21),
 (31214, '17th & Corcoran St NW', None, 30),
 (31034, 'N Randolph St & Fairfax Dr', None, 13),
 (31260, '23rd & E St NW ', None, 6),
 (31291, '16th & K St NW', None, 8),
 (31801, 'Anacostia Metro', None, 14),
 (32001, 'Fenton St & New York Ave ', None, 7),
 (31025, 'Central Library / N Quincy St & 10th St N', None, 6),
 (31037, 'Ballston Metro / N Stuart & 9th St N', None, 7),
 (31023, 'Fairfax Dr & Wilson Blvd', None, 14),
 (31234, '20th & O St NW / Dupont South', None, 9),
 (31412, '3rd St & Riggs Rd NE', None, 20),
 (31078, 'Arlington Blvd & S George Mason Dr/NFATC', None, 8),
 (31273, 'Hains Point/Buckeye & Ohio Dr SW', None, 19),
 (31637, 'North Capitol St & G Pl NE', None, 6),
 (31406, '14th & Upshur St NW', None, 7),
 (32032, 'Fleet St & Ritchie Pkwy', None, 17),
 (31305, 'Connecticut Ave & Newark St NW / Cleveland Park', None, 16),
 (31019, 'Wilson Blvd & N Edgewood St', None, 13),
 (31606, 'Potomac & Pennsylvania Ave SE', None, 15),
 (31914, 'Lee Center', None, 16),
 

In the __Rider__ dataset, there are 5 members we just created. Rider ID, rider name, address, last membership type, key status, last purchase date, active status and last expire date is all included in this dataset.

In [18]:
%%sql
SELECT * FROM Rider;

5 rows affected.


[('001', 'Connie', '1600 S Eads St', 'annual', 'sent', datetime.datetime(2017, 6, 15, 0, 0), 'Yes', datetime.datetime(2018, 6, 15, 0, 0)),
 ('002', 'Pei-Hsuan', '2121 I St', 'annual', 'sent', datetime.datetime(2017, 3, 13, 0, 0), 'Yes', datetime.datetime(2018, 3, 13, 0, 0)),
 ('003', 'Guangyu', '2201 G St', 'semiannual', 'sent', datetime.datetime(2017, 6, 30, 0, 0), 'Yes', datetime.datetime(2017, 12, 31, 0, 0)),
 ('004', 'Wayne', '2000 H St', 'semiannual', 'sent', datetime.datetime(2017, 7, 15, 0, 0), 'Yes', datetime.datetime(2018, 1, 15, 0, 0)),
 ('005', 'Agnes', '1900 S Eads St', 'monthly', 'returned', datetime.datetime(2017, 8, 26, 0, 0), 'No', datetime.datetime(2017, 9, 26, 0, 0))]

### Problem 4.1
The bike 'W20131' is having mechanical problems and needs to be repaired off-site. Use SQL UPDATE statements to record the fact that this bike is no longer serviceable and has been removed from the station where it was docked at.

First, show all of the current information of  the bike W20131.

In [19]:
%%sql
SELECT * FROM Bike
WHERE bikeid = 'W20131';

1 rows affected.


[('W20131', None, 't', 31060)]

Then, since the bike W20131 is broken, we update its status as non-serviceable. That is, change its serviceable content to “f”. 

In [20]:
%%sql
UPDATE Bike 
SET    serviceable = 'f'
WHERE  bikeid = 'W20131';

1 rows affected.


[]

Finally, show the update result to check whether it is changed.


In [21]:
%%sql
SELECT * FROM Bike
WHERE bikeid = 'W20131';

1 rows affected.


[('W20131', None, 'f', 31060)]

### Problem 4.2
The bike station at Adams Mill & Columbia Rd NW has been expanded. Use SQL UPDATE statements to change the name of the bike station from "Adams Mill & Columbia Rd NW" to "18th & Columbia Rd NW" and increase its capacity by 10.

First, select the record with required station name and get its station ID from __BikeStation__ table.

In [22]:
%%sql
SELECT * FROM BikeStation
WHERE stationname = 'Adams Mill & Columbia Rd NW';

1 rows affected.


[(31104, 'Adams Mill & Columbia Rd NW', None, 4)]

Then, update the record where stationID is the one we just picked. Record the previous station name into formername column, change its station name to the new name, and update the capacity to 10.

In [23]:
%%sql
UPDATE BikeStation 
SET    formername = stationname, stationname = '18th & Columbia Rd NW', capacity = 10
WHERE  stationid = 31104;

1 rows affected.


[]

Finally, verify the record is successfully updated.

In [24]:
%%sql
SELECT * FROM BikeStation
WHERE stationid = 31104;

1 rows affected.


[(31104, '18th & Columbia Rd NW', 'Adams Mill & Columbia Rd NW', 10)]

### Problem 4.3
Use SQL UPDATE and/or INSERT statements to record the transaction that an active member checked out the bike 'W00005' from station 'Maple & Ritchie Ave' at '2017-10-01 08:46:00'.

Confirm that there is no record in the __Transaction__ table.

In [25]:
%%sql
SELECT * FROM Transaction;

0 rows affected.


[]

This query is to record the transaction that member '003' checked out the bike 'W00005' from station 'Maple & Ritchie Ave' at '2017-10-01 08:46:00'.  
Line 3 extract the stationID of station 'Maple & Ritchie Ave' into startstationid from __BikeStation__ table.   
Last line check if the transaction is successfully updated.

In [26]:
%%sql
INSERT INTO Transaction (transactionid, bikeID, riderID, servicestatus, startstationid, startdate)
SELECT 'T001' AS transactionid, bikeID, '003' AS riderID, 'checked out' AS servicestatus,
       (SELECT stationid FROM BikeStation WHERE stationname = 'Maple & Ritchie Ave') AS startstationid, 
       '2017-10-01 08:46:00' AS startdate
FROM  Bike
WHERE bikeid = 'W00005';

SELECT * FROM Transaction;

1 rows affected.
1 rows affected.


[('T001', 'W00005', '003', 'checked out', 32011, datetime.datetime(2017, 10, 1, 8, 46), None, None)]

The transaction query is to update the 'bikestatus' column accordingly when the 'servicestatus' column in the  __Transaction__ table is updated.

In [27]:
%%sql
START  TRANSACTION;
UPDATE Bike SET bikeStatus = A.servicestatus
FROM  (SELECT DISTINCT bikeID, serviceStatus
       FROM  (SELECT bikeID, serviceStatus, startdate
              FROM  Transaction
              ORDER BY startdate DESC
             ) AS B
      ) AS A
WHERE Bike.bikeID = A.bikeID;
COMMIT;

Done.
1 rows affected.
Done.


[]

Verify that bikestatus is changes in the __Bike__ table.

In [28]:
%%sql
SELECT * FROM Bike
WHERE bikeID = 'W00005';

1 rows affected.


[('W00005', 'checked out', 't', 32011)]

## Part 5 - Queries (20 points)

Use SQL SELECT statements to answer the following questions. Use markdown cells to explain your SQL statements and results if needed.

### Problem 5.1
For all members, display their name, membership type (annual, semiannual or monthly, in readable text), membership status (active or expired, boolean value is fine) and the date when the membership expires.

Select and show the columns of name, lastMemberType, activeStatus, and lastExpireDate in the __Rider__ table.

In [29]:
%%sql
SELECT name, lastMembertype, activeStatus, lastExpireDate
FROM   Rider;

5 rows affected.


[('Connie', 'annual', 'Yes', datetime.datetime(2018, 6, 15, 0, 0)),
 ('Pei-Hsuan', 'annual', 'Yes', datetime.datetime(2018, 3, 13, 0, 0)),
 ('Guangyu', 'semiannual', 'Yes', datetime.datetime(2017, 12, 31, 0, 0)),
 ('Wayne', 'semiannual', 'Yes', datetime.datetime(2018, 1, 15, 0, 0)),
 ('Agnes', 'monthly', 'No', datetime.datetime(2017, 9, 26, 0, 0))]

### Problem 5.2
Display the first 10 bikes base on the bike number in ascending order. For each bike, list its status (serviceable or disabled, boolean value is fine), the station name where it is docked at if there is any, the member if the bike is currently checked out, and when it was checked out. Hint: you should see one disabled bike and one checked out bike.

First, select bikeID and serviceable columns of __Bike__ table, and join the subquery of __Bike__ table where there is no lastStationID if the bike is checked out. Then, show the station name in the subquery of __Bike__ table by joining the __BikeStation__ table.
Finally, join the __Transaction__ table and __rider__ table to show borrower name and the time when he borrowed the bike.


In [30]:
%%sql
SELECT B.bikeID, B.serviceable , B.bikeStatus, BS.stationName , R.name, T.startDate  
FROM   Bike AS B

LEFT JOIN 
    (SELECT bikeID, lastStationID 
     FROM Bike
     WHERE bikeStatus is null
    ) AS A
ON B.bikeID = A.bikeID

LEFT JOIN BikeStation AS BS 
ON A.laststationID = BS.stationID

LEFT JOIN Transaction AS T 
ON T.bikeID = B.bikeID

LEFT JOIN Rider AS R 
ON T.riderID = R.riderID

ORDER BY B.bikeID
LIMIT 10;

10 rows affected.


[('W00001', 't', None, 'Ward Circle / American University', None, None),
 ('W00005', 't', 'checked out', None, 'Guangyu', datetime.datetime(2017, 10, 1, 8, 46)),
 ('W00007', 't', None, 'Gallaudet / 8th St & Florida Ave NE', None, None),
 ('W00009', 't', None, 'Mount Vernon Ave & Bruce St', None, None),
 ('W00010', 't', None, 'Jefferson Memorial', None, None),
 ('W00011', 'f', None, None, None, None),
 ('W00012', 't', None, 'Wilson Blvd & N Illinois St ', None, None),
 ('W00013', 't', None, 'Lee Center', None, None),
 ('W00014', 't', None, 'Wilson Blvd & N Illinois St ', None, None),
 ('W00015', 't', None, 'Saint Asaph St & Pendleton  St', None, None)]

### Problem 5.3
Display the top 10 stations which currently have the most bikes docked. For each station, list the station name and the total number of bikes docked there.

First, we selected the 'bikeid' and 'lastStationID' of bikes that are docked in the bike station from the __Bike__ table. In the result of subquery, 'lastStationID' was substituted by station name and 'bikeid' counted by station name, which equaled to the number of bikes docked in a station. Finally we ranked the station by number of bikes docked in descending order.

In [31]:
%%sql
SELECT (SELECT BikeStation.stationname
        FROM BikeStation
        WHERE A.laststationid = BikeStation.stationID) AS stationname,
       count(A.bikeid) AS dock_no
FROM
(SELECT bikeid,
       lastStationID
FROM   bike
WHERE  (bikestatus <> 'checked out' OR bikestatus is null) and serviceable = 't') AS A
GROUP BY stationname
ORDER BY dock_no DESC
LIMIT 10;

10 rows affected.


[('Columbus Circle / Union Station', 49),
 ('14th & V St NW', 41),
 ('2nd & G St NE', 36),
 ('13th & D St NE', 33),
 ('12th & U St NW', 32),
 ('11th & Kenyon St NW', 29),
 ('1st & N St  SE', 28),
 ('13th & H St NE', 27),
 ('6th & H St NE', 27),
 ('4th & M St SW', 27)]

### Problem 5.4
Display the first 10 stations based on their names in ascending order. For each station, list station name and the number of available docking points accepting bike returns. Verify the numbers are correct.

First, we counted the number of bikes docked by bike station. Then we add the number of bikes docked into __BikeStation__ table and obtained the number of points avaible by capacity minus the number of bikes docked. Finally, we ranked 'stationname' in ascending order and display top 10.

In [32]:
%%sql
SELECT BikeStation.stationID, BikeStation.stationname, BikeStation.capacity, B.dock_no, 
(BikeStation.capacity - B.dock_no) AS point_avail FROM BikeStation
LEFT OUTER JOIN
    (SELECT laststationid,count(bikeid) as dock_no
       FROM Bike
      WHERE  (bikestatus <> 'checked out' OR bikestatus is null) and serviceable = 't'
      GROUP BY laststationid) AS B
ON BikeStation.stationID = B.laststationID
ORDER BY BikeStation.stationname
LIMIT 10;

10 rows affected.


[(31256, '10th & E St NW', 17, 15, 2),
 (31120, '10th & Florida Ave NW', 21, 16, 5),
 (31274, '10th & G St NW', 14, 6, 8),
 (31263, '10th & K St NW', 14, 8, 6),
 (31504, '10th & Monroe St NE', 3, 1, 2),
 (31219, '10th St & Constitution Ave NW', 13, 8, 5),
 (31287, "10th St & L'Enfant Plaza SW", 8, 1, 7),
 (31111, '10th & U St NW', 17, 15, 2),
 (31262, '11th & F St NW', 8, 6, 2),
 (31614, '11th & H St NE', 23, 20, 3)]

### _We first read the instructions and built draft schema individually. Then we met together to come up with a final schema and worked together with the rest questions. We all contributed substantially to the work._